### ISSUE TITLE
Need illustrator open .ait script

### ISSUE THREAD

**Issue by sgops27** [Inventsable/Tilebox#1]
I have created some illustrator template files (.ait) placed in my local D drive (path),
Ex: 00_Helvetica_27 x 40, 00_Helvetica_28 x 47 (and Many)

once I run the script open that popup template file (attached i create the screenshot) window and select what file i need then hit OK open that file.

it's passable in javascript
![WhatsApp Image 2019-02-28 at 9 57 11 AM](https://user-images.githubusercontent.com/47688301/54736964-b0542d00-4bd3-11e9-892c-988e27b0e527.jpeg)

**Comment by Inventsable** [comment]
Please do not use my repository for general Q&A or scripting requests. This has nothing to do with my extension and you've posted duplicates of this issue in random Illustrator-related repos.

Try reddit for help or the Adobe scripting forum. Creating issues on github pages is probably the worst way to go about asking for help because it implies there's something wrong with their existing work.
